# Generated by Django 3.2.13 on 2022-04-24 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GitIntouch',
            new_name='GetIntouch',
        ),
    ]
