# Generated by Django 3.2.13 on 2022-04-24 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_gitintouch_getintouch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ('-id',), 'verbose_name': 'Service', 'verbose_name_plural': 'Servislar'},
        ),
    ]
