# Generated by Django 3.2.13 on 2022-04-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_finish', models.CharField(max_length=255)),
                ('type', models.IntegerField(choices=[(0, 'Education'), (1, 'Experience'), (2, 'Skills'), (3, 'Awards')])),
                ('profession', models.CharField(max_length=255)),
                ('academy', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to='icon')),
                ('content', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ImageField(upload_to='icon')),
            ],
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('birth', models.DateField()),
                ('live', models.CharField(max_length=255)),
                ('zip_code', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=255)),
                ('tag', models.ManyToManyField(to='person.Tag')),
            ],
        ),
    ]
