# Generated by Django 3.2.13 on 2022-04-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='academy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icon'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='is_skill',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='profession',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='start_finish',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
