# Generated by Django 3.2.13 on 2022-04-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20220424_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='is_skill',
            field=models.BooleanField(default=False),
        ),
    ]
