# Generated by Django 3.2.13 on 2022-04-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_alter_resume_is_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='projects',
            field=models.IntegerField(default=120),
            preserve_default=False,
        ),
    ]
