# Generated by Django 3.2.13 on 2022-04-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_about_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='academy',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='content',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='start_finish',
        ),
        migrations.AddField(
            model_name='skill',
            name='academy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icon'),
        ),
        migrations.AddField(
            model_name='skill',
            name='profession',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='start_finish',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='type',
            field=models.CharField(max_length=221),
        ),
    ]
