# Generated by Django 3.2.13 on 2022-04-25 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_auto_20220425_1521'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skill',
            new_name='AdditionalInfo',
        ),
    ]
