# Generated by Django 3.2.13 on 2022-04-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_rename_skill_additionalinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='percent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='title',
            field=models.CharField(blank=True, max_length=221, null=True),
        ),
    ]
