# Generated by Django 3.2.13 on 2022-04-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_auto_20220425_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalinfo',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
